version: '3.8'

networks:
  my-network:
    external: true

services:

  kong-database:
    image: postgres:14.4-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kongpass
      - POSTGRES_DB=kong
    networks:
      - my-network

  kong-migration:
    image: kong:3.2.2-alpine
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
      KONG_PASSWORD: test
    depends_on:
      - kong-database
    entrypoint:
      - "kong"
      - "migrations"
      - "bootstrap"
    networks:
      - my-network

  kong-gateway:
    image: kong:3.2.2-alpine
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
      - kong-migration
    ports:
      - "8000"
      - "8001"
      - "8443"
      - "8444"
    networks:
      - my-network
